### ISSUE TITLE
Failed to connect to Spotify

### ISSUE THREAD

**Issue by steadfasterX** [Bleuzen/SpotRec#7]
what is the intended way to run spotify? I mean I have the web player running as I am not aware of any native spotify client on linux. I even tried spotify-qt which also gets identified by pavucontrol as "Chrome". Pulseaudio is running ofc.. What do I miss here?
Package has been installed from AUR (running Manjaro Linux here)

```
spotrec --debug -s -u -o /home/foo/Musik/
2020-09-25 17:24:25,840 - DEBUG - Logger initialized
2020-09-25 17:24:25,842 - ERROR - Failed to connect to Spotify. (Maybe it's not running yet?)
```

![2020-09-25_17-27](https://user-images.githubusercontent.com/8750713/94286098-d68b2380-ff54-11ea-8416-61cb8828b4d9.png)

as you can see it looks like there is no recording device which would be spotrec I guess. but as that cannot be started.. :

![2020-09-25_17-27_1](https://user-images.githubusercontent.com/8750713/94286102-d723ba00-ff54-11ea-98f4-134f2b1abb50.png)

realized that maybe I need to install the package **[spotifyd](https://www.archlinux.org/packages/community/x86_64/spotifyd/)** and I did that as well - looking correctly connected:

![image](https://user-images.githubusercontent.com/8750713/94287949-2ec32500-ff57-11ea-883b-2b39faefb9a8.png)

but even now -- nothing changed at all. everything still the same. same error by spotrec and screens look identical.

**Comment by steadfasterX** [comment]
ok... got it.

`snap install spotify`

then it runs as it should..

**Comment by Bleuzen** [comment]
This script only works with the Spotify desktop client for Linux.
On Manjaro there are 3 ways to install it:
1) AUR (`spotify`)
2) Flatpak (`flatpak install flathub com.spotify.Client`)
3) Snap (`snap install spotify`)

SpotRec supports all 3 versions, however I would recommend using Flatpak.
Downside of the AUR package: it is not sandboxed
Downside of Snap: it has auto updates you can't disabled and the server side is proprietary and owned by Canonical
So there is Flatpak left as the best option in my opinion. But you can use all three if you want to.
The web player is not supported

**Comment by steadfasterX** [comment]
thx for your reply @Bleuzen !
I would recommend to add exact your above answer to the README ! :)
